# Generated by Django 4.2.4 on 2023-08-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_subscription_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
